name: CI
on:
  push:
    branches: [ main, "feat/**", "chore/**" ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
      - name: Lint
        run: pre-commit run --all-files
      - name: Tests
        run: |
          python -m pytest --maxfail=1 -q
